### PR TITLE
isodd and sin math functions

### PR DESCRIPTION
**Pull request by connorlien**
## Overview

- Create executors and tests for the ISODD and SIN functions.

## Changes

- Created a new file mathfuncexecutor.py that will contain executors for all math functions
  - Created a general function to get single function values from an execution node
- Wrote executors for ISODD and SIN, and tested them
  - Both E2E tests with formula strings and executor-specific tests

## Example Output

- If you pass in a single column dataframe to the executor, it should return a single column dataframe with the desired results

### CODE REVIEW

**Comment by totemtang** [comment]
This commit is conflicted with the existing code. Please merge the up-to-date code to your own fork.

**Comment by totemtang** [comment]
The black format check failed. Please use "make reformat". Also, try "make test" before submitting the commit. I think you need to register the respective functions.

**Comment by totemtang** [comment]
There are conflicts to merge your commit into the main branch. Can you resolve the conflicts locally?

**Comment by connorlien** [comment]
@totemtang resolved!

**Pull request merged**
